# Generated by Django 5.0.4 on 2024-04-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
