# Generated by Django 5.0.4 on 2024-04-11 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_remove_factura_productos_factura_productos'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='productos',
        ),
        migrations.AddField(
            model_name='factura',
            name='productos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.productos'),
        ),
    ]
